FROM mysql:5.7

RUN usermod -u 1000 mysql
RUN mkdir -p /var/run/mysqld
RUN chmod -R 777 /var/run/mysqld
ENV MYSQL_USER edenuser 
ENV MYSQL_PASSWORD cs6440
ENV MYSQL_DATABASE eden
ENV MYSQL_ROOT_PASSWORD cs6440

